'use strict';

export enum RoleType {
    USER = 'ROLE_USER',
    ADMIN = 'ROLE_ADMIN',
    ANONYMOUS = 'ROLE_ANONYMOUS',
    RECEPTIONIST = 'ROLE_RECEPTIONIST',
    PRODUCTION = 'ROLE_PRODUCTION',
    LABORATORY = 'ROLE_LABORATORY',
}
